// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int32) (Account, error)
	GetAccountsGraphs(ctx context.Context, arg GetAccountsGraphsParams) (int64, error)
	GetAccountsReports(ctx context.Context, arg GetAccountsReportsParams) (int64, error)
	GetCategoryById(ctx context.Context, id int32) (Category, error)
	GetCategoryByUserId(ctx context.Context, arg GetCategoryByUserIdParams) ([]Category, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
}

var _ Querier = (*Queries)(nil)
