// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int32) error
	GetCategoryById(ctx context.Context, id int32) (Category, error)
	GetCategoryByUserId(ctx context.Context, arg GetCategoryByUserIdParams) ([]Category, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
}

var _ Querier = (*Queries)(nil)
